# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listSummary', '0002_auto_20160218_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='vino_transferSummary1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanaName', models.CharField(db_column=b'kanaName', max_length=12000, null=True)),
                ('itemPrice', models.FloatField(db_column=b'itemPrice', null=True)),
                ('itemPriceDeviation', models.FloatField(db_column=b'itemPriceDeviation', null=True)),
                ('itemPriceCoefficientVariation', models.FloatField(db_column=b'itemPriceCoefficientVariation', null=True)),
                ('years', models.CharField(db_column=b'years', max_length=255, null=True)),
                ('mlVolume', models.CharField(db_column=b'mlVolume', max_length=255, null=True)),
                ('reviewAvarage', models.FloatField(db_column=b'reviewAvarage', null=True)),
                ('reviewCount', models.IntegerField(db_column=b'reviewCount', null=True)),
                ('tasteType', models.CharField(db_column=b'tasteType', max_length=255, null=True)),
                ('countryIds', models.CharField(db_column=b'countryId', max_length=1000, null=True)),
                ('regionIds', models.CharField(db_column=b'regionId', max_length=1000, null=True)),
                ('grapeIds', models.CharField(db_column=b'grapeIds', max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='vino_transferSummary',
        ),
    ]
