# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listSummary', '0004_auto_20160222_2040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vino_transferSummary',
            new_name='vino_transferSummary1',
        ),
    ]
