# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listSummary', '0008_auto_20160222_2051'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vino_transfersummary',
            table='vino_transferSummary1',
        ),
    ]
