# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listSummary', '0011_vino_transfersummary_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vino_transfersummary_year',
            name='summaryId',
            field=models.ForeignKey(default=datetime.datetime(2016, 2, 28, 14, 43, 36, 8000, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='listSummary.vino_transferSummary'),
            preserve_default=False,
        ),
    ]
