# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listSummary', '0016_auto_20160229_2335'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testvinogrape',
            table='testVinoGrape1',
        ),
    ]
