# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listSummary', '0017_auto_20160229_2346'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testvinogrape',
            table='testVinoGrape',
        ),
    ]
