# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listSummary', '0025_auto_20160302_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vino_transfersummary_tastetype',
            name='summaryId',
            field=models.ForeignKey(db_column=b'summaryId', on_delete=django.db.models.deletion.CASCADE, to='listSummary.vino_transferSummary'),
        ),
        migrations.AlterField(
            model_name='vino_transfersummary_year',
            name='summaryId',
            field=models.ForeignKey(db_column=b'summaryId', on_delete=django.db.models.deletion.CASCADE, to='listSummary.vino_transferSummary'),
        ),
    ]
