# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listSummary', '0028_auto_20160302_1838'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vino_transfersummary_year',
            table='vino_transferSummary_Year1',
        ),
    ]
