# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listSummary', '0030_auto_20160302_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vino_transfersummary_year',
            name='summaryId',
            field=models.ForeignKey(db_column=b'summaryId', on_delete=django.db.models.deletion.CASCADE, to='listSummary.vino_transferSummary'),
        ),
        migrations.AlterField(
            model_name='vino_transfersummary_year',
            name='year',
            field=models.IntegerField(db_column=b'years', null=True),
        ),
        migrations.AlterModelTable(
            name='vino_transfersummary_year',
            table='vino_transferSummary_Year',
        ),
    ]
