# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listSummary', '0031_auto_20160302_2003'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taggrape',
            table='tagGrape',
        ),
    ]
